export default function Terms() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-[#0a0a0a] to-[#1a1a1a] flex items-center justify-center p-4 font-sans text-white">
      <div className="w-full max-w-3xl bg-gradient-to-br from-[#111111] to-[#0f0f0f] border border-[#2a2a2a] rounded-2xl p-10 shadow-2xl">
        <h1 className="text-4xl font-bold mb-8 tracking-tight bg-gradient-to-r from-white to-gray-400 bg-clip-text text-transparent">
          Terms of Service
        </h1>
        <p className="text-gray-300 mb-8 leading-relaxed text-lg">
          Welcome to ClientBrain! By using our services, you agree to the following terms and conditions. Please read them carefully.
        </p>
        
        <div className="border-t border-[#2a2a2a] pt-8">
          <h2 className="text-2xl font-bold mb-6 text-white">Data Processing</h2>
          <p className="text-gray-300 mb-6 leading-relaxed text-base">
            The resumes are being generated by the GPT-4 model. That means your data is being sent to OpenAI's servers for processing.
          </p>
        </div>
      </div>
    </div>
  )
}

